/**
 * Generate the analytics module.
 *
 * Everything in the emitted file is there because its absence caused a real
 * production failure that no test and no local run could have caught. In order:
 *
 *   1. `$pageview` is sent by hand. posthog-js's `history_change` mode captures
 *      on history changes only, so a full page load - every direct visit and
 *      every reload - sent `$pageleave` with no matching `$pageview`, and Web
 *      Analytics read zero while events flowed normally.
 *   2. URL sanitisation keeps the origin. Rewriting `$current_url` down to a
 *      bare path strips the ids, and also strips the domain Web Analytics parses
 *      to attribute a visit, so every visit attributed to nothing.
 *   3. Replay catches up to the landing route after the SDK loads. The dynamic
 *      import means the first route effect runs while the instance is still
 *      null, so recording only ever started on the first in-app navigation, and
 *      land-look-leave sessions - the ones most worth watching - were exactly
 *      the ones never recorded.
 *   4. Events fired before init are queued, bounded. Boot-time events are the
 *      ones a funnel most needs and the ones most likely to be dropped.
 *   5. Autocapture, heatmaps, dead clicks, rageclicks and web experiments are
 *      off. A new button cannot start reporting itself, and a share code in a
 *      URL cannot become a property.
 *
 * The generated file has no dependency on OpenHog. It is yours; edit it.
 */

import type { TrackingPlan } from '../types.js'

export interface EmitOptions {
  plan: TrackingPlan
  /** Env var holding the phc_ project key. */
  publicKeyEnv: string
  ingestHost: string
  /** 'vite' uses import.meta.env, 'next' and 'node' use process.env. */
  envStyle: 'vite' | 'next' | 'process'
  /** Emit the `posthog-js` import, or leave the SDK to the caller. */
  includeSdk?: boolean
}

function envAccess(style: EmitOptions['envStyle'], name: string): string {
  return style === 'vite' ? `import.meta.env.${name}` : `process.env.${name}`
}

/** Route patterns → the `normalizeRoute` body, longest prefix first. */
function normalizeRouteBody(routes: string[]): string {
  const dynamic = routes
    .filter((route) => route.includes('/:'))
    .sort((a, b) => b.length - a.length)

  if (dynamic.length === 0) {
    return "  return path.length > 254 ? path.slice(0, 254) : path"
  }

  const lines = dynamic.slice(0, 60).map((route) => {
    // '/events/:id' → /^\/events\/[^/]+/ . Anything after the first param is
    // matched loosely, because a nested id would otherwise need its own rule.
    const prefix = route.slice(0, route.indexOf('/:'))
    const escaped = prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const suffix = route.slice(route.indexOf('/:'))
    const paramCount = (suffix.match(/\/:/g) ?? []).length
    const tail = '\\/[^/]+'.repeat(paramCount)
    return `  if (/^${escaped}${tail}/.test(path)) return '${route}'`
  })

  return `${lines.join('\n')}\n  return path.length > 254 ? path.slice(0, 254) : path`
}

export function emitAnalyticsModule(options: EmitOptions): string {
  const { plan, publicKeyEnv, ingestHost, envStyle } = options
  const emitted = plan.events.filter((event) => event.emitted)
  const names = (emitted.length ? emitted : plan.events).map((event) => event.name)
  const keyExpr = envAccess(envStyle, publicKeyEnv)
  const hostExpr = envAccess(envStyle, `${publicKeyEnv.replace(/KEY$/, '')}HOST`)
  const replayExpr = envAccess(envStyle, `${publicKeyEnv.replace(/KEY$/, '')}SESSION_RECORDING`)

  return `/**
 * Analytics. Generated by OpenHog, then owned by you.
 *
 * One chokepoint: every event in the product goes through \`track()\`, which is
 * why adding a sink later is a change in one file rather than in two hundred.
 *
 * Four rules this file enforces in code rather than in a document:
 *
 *   - Only events named in EVENT_NAMES are sent, plus \`$pageview\` and
 *     \`$pageleave\`, which PostHog's Web Analytics is built on. Autocapture is
 *     off, so a new button cannot start reporting itself.
 *   - URLs are normalised before they leave the browser. \`/items/8f2c\` becomes
 *     \`/items/:id\`, so an id never becomes a property value.
 *   - Nothing here ever throws into your app. A dropped analytics event is
 *     always cheaper than a broken render.
 *   - No key, no PostHog. Without ${publicKeyEnv} every export is inert, which is
 *     what dev, test and preview builds get by default.
 *
 * Regenerate the type list with \`openhog sync\`; keep your own edits below the
 * EVENT_NAMES array, which is the only part OpenHog rewrites.
 */

import type { PostHog, PostHogConfig, Properties } from 'posthog-js'

/* --- openhog:events:start --- */
export const EVENT_NAMES = [
${names.map((name) => `  '${name}',`).join('\n')}
] as const
/* --- openhog:events:end --- */

export type EventName = (typeof EVENT_NAMES)[number]
export type PropertyValue = string | number | boolean | null
export type EventProperties = Record<string, PropertyValue | undefined>

/**
 * Replay and verbose capture stay off these routes entirely. Masking an input is
 * one thing; recording the shape of somebody's inbox or their billing details is
 * another, and no masking selector makes that safe.
 *
 * Add a route here the moment it starts showing someone else's personal data.
 */
export const SENSITIVE_ROUTES: string[] = [
${plan.identity.sensitiveRoutes.map((route) => `  '${route}',`).join('\n')}
]

/** PostHog stamps these onto every capture, and each one carries a raw URL. */
const URL_PROPERTIES = [
  '$current_url',
  '$initial_current_url',
  '$pathname',
  '$initial_pathname',
  '$referrer',
  '$initial_referrer',
] as const

const MAX_QUEUED_EVENTS = 50
const MAX_STRING_LENGTH = 254

let client: PostHog | null = null
let loading: Promise<void> | null = null
let queue: { name: string; properties: EventProperties }[] = []
let pendingDistinctId: string | null = null
let identifiedId: string | null = null
let replayEnabled = false
let replayActive = false
let lastPageviewRoute: string | null = null
let disabled = false

/**
 * Collapse a path to a route pattern. This is the single most important
 * function in the file: without it, every id in every URL becomes a distinct
 * property value, breakdowns turn into ten-thousand-row lists, and the bill
 * follows.
 */
export function normalizeRoute(pathname: string | null | undefined): string {
  const path = pathname?.split(/[?#]/)[0] || '/'
  if (path === '/') return '/'
${normalizeRouteBody(plan.routes ?? [])}
}

export function isSensitiveRoute(pathname: string): boolean {
  return SENSITIVE_ROUTES.some((route) => pathname === route || pathname.startsWith(route + '/'))
}

function normalizeUrlProperty(value: unknown): string | null {
  if (typeof value !== 'string' || !value) return null
  const RELATIVE_BASE = 'https://openhog.invalid'
  try {
    const url = new URL(value, RELATIVE_BASE)
    const route = normalizeRoute(url.pathname)
    // Keep the origin on absolute URLs. Web Analytics reads $current_url to
    // attribute a visit to a domain, and a bare path attributes to nothing -
    // which reads as zero visitors while events flow normally. The origin was
    // never the sensitive part: the ids in the path and the query string are,
    // and both are still rewritten away here.
    return url.origin === RELATIVE_BASE ? route : url.origin + route
  } catch {
    return normalizeRoute(value.split(/[?#]/)[0] || '/')
  }
}

export function sanitizeProperties(properties: Properties): Properties {
  const sanitized: Properties = { ...properties }
  for (const key of URL_PROPERTIES) {
    if (!(key in sanitized)) continue
    const normalized = normalizeUrlProperty(sanitized[key])
    if (normalized === null) delete sanitized[key]
    else sanitized[key] = normalized
  }
  return sanitized
}

/** Drop anything that is not a scalar rather than stringifying it. */
export function sanitizeEventProperties(
  properties: Record<string, unknown> = {},
): Record<string, PropertyValue> {
  const clean: Record<string, PropertyValue> = {}
  for (const [rawKey, value] of Object.entries(properties)) {
    const key = rawKey.trim().slice(0, MAX_STRING_LENGTH)
    if (!key || value === undefined) continue
    if (value === null) clean[key] = null
    else if (typeof value === 'string') clean[key] = value.slice(0, MAX_STRING_LENGTH)
    else if (typeof value === 'number') { if (Number.isFinite(value)) clean[key] = value }
    else if (typeof value === 'boolean') clean[key] = value
  }
  return clean
}

export function buildConfig(host: string, sessionRecording: boolean): Partial<PostHogConfig> {
  return {
    api_host: host,
    // Everything that would report an interaction nobody named.
    autocapture: false,
    capture_heatmaps: false,
    capture_dead_clicks: false,
    rageclick: false,
    disable_web_experiments: true,
    disable_surveys: true,
    // $pageview is sent by hand from syncRoute(). The SDK's 'history_change'
    // mode captures on history changes only, so a full page load - every direct
    // visit and every reload - produced $pageleave with no matching $pageview,
    // and Web Analytics read zero.
    capture_pageview: false,
    // Left to the SDK: bounce rate and session duration need it, and it has to
    // fire during unload, which is not a moment application code can own.
    capture_pageleave: true,
    // Replay pulls its recorder in over the network. With replay off there is no
    // reason for this origin to fetch any further third-party script.
    disable_external_dependency_loading: !sessionRecording,
    disable_session_recording: true,
    session_recording: {
      maskAllInputs: true,
      maskTextClass: 'ph-mask',
      maskTextSelector: '[data-ph-mask]',
      collectFonts: false,
      recordHeaders: false,
      recordBody: false,
    },
    respect_dnt: true,
    disable_capture_url_hashes: true,
    mask_personal_data_properties: true,
    person_profiles: 'identified_only',
    persistence: 'localStorage+cookie',
    secure_cookie: true,
    sanitize_properties: sanitizeProperties,
  }
}

function flush(): void {
  if (!client) return
  const pending = queue
  queue = []
  for (const item of pending) {
    try {
      client.capture(item.name, item.properties)
    } catch {
      // A dropped analytics event never justifies breaking the app.
    }
  }
}

/**
 * Start PostHog. Safe to call repeatedly; only the first call with a usable key
 * does anything. Without a key this resolves immediately and every later call
 * stays inert, which is what dev, test and preview builds get by default.
 */
export function initAnalytics(options: { distinctId?: string | null } = {}): Promise<void> {
  if (loading) return loading

  const key = ${keyExpr}
  if (!key || typeof window === 'undefined') {
    disabled = true
    queue = []
    loading = Promise.resolve()
    return loading
  }

  const host = ${hostExpr} || '${ingestHost}'
  replayEnabled = ${replayExpr} === 'true'

  loading = import('posthog-js')
    .then((mod) => {
      const instance = mod.default
      instance.init(key, buildConfig(host, replayEnabled))
      client = instance
      const id = options.distinctId ?? pendingDistinctId
      if (id) {
        pendingDistinctId = null
        identify(id)
      }
      flush()
      // The route effect already ran for the landing route while this import
      // was in flight and \`client\` was null. Without this catch-up, replay only
      // ever begins on the first in-app navigation, so land-look-leave sessions
      // are exactly the ones never recorded - and the landing $pageview is lost.
      if (typeof window !== 'undefined') syncRoute(window.location.pathname)
    })
    .catch(() => {
      // Blocked by an extension, offline, or a bad key. Never surface this.
      queue = []
    })

  return loading
}

/** Bind PostHog's distinct_id. Calling it again with the same id is a no-op. */
export function identify(distinctId: string | null | undefined): void {
  if (!distinctId || disabled) return
  if (!client) {
    pendingDistinctId = distinctId
    return
  }
  if (identifiedId === distinctId) return
  identifiedId = distinctId
  try {
    client.identify(distinctId)
  } catch {
    identifiedId = null
  }
}

/** The one chokepoint. Every event in the product goes through here. */
export function track(name: EventName, properties: Record<string, unknown> = {}): void {
  if (disabled) return
  const clean = sanitizeEventProperties(properties)
  if (!client) {
    // Also covers events fired before initAnalytics runs. Boot-time events are
    // the ones a funnel most needs, so they queue rather than drop. The queue is
    // bounded and discarded outright if init never happens.
    if (queue.length >= MAX_QUEUED_EVENTS) queue.shift()
    queue.push({ name, properties: clean })
    return
  }
  try {
    client.capture(name, clean)
  } catch {
    // Same reasoning as flush().
  }
}

/**
 * Call on every route change, and once on mount. Sends exactly one $pageview per
 * route and starts or stops replay for sensitive routes.
 */
export function syncRoute(pathname: string): void {
  if (!client) return

  if (lastPageviewRoute !== pathname) {
    lastPageviewRoute = pathname
    try {
      client.capture('$pageview')
    } catch {
      // Never break navigation for a metric.
    }
  }

  if (!replayEnabled) return
  const shouldRecord = !isSensitiveRoute(pathname)
  if (shouldRecord === replayActive) return
  replayActive = shouldRecord
  try {
    if (shouldRecord) client.startSessionRecording()
    else client.stopSessionRecording()
  } catch {
    replayActive = !shouldRecord
  }
}

/** Test seam. Not for production use. */
export function resetAnalyticsForTests(): void {
  client = null
  loading = null
  queue = []
  pendingDistinctId = null
  identifiedId = null
  replayEnabled = false
  replayActive = false
  lastPageviewRoute = null
  disabled = false
}
`
}

/** The snippet that wires init into an app entry point, per framework. */
export function emitWiringSnippet(framework: string, modulePath: string): string {
  const importPath = modulePath.replace(/\.tsx?$/, '')
  if (framework === 'nextjs') {
    return `'use client'
import { useEffect } from 'react'
import { usePathname } from 'next/navigation'
import { initAnalytics, syncRoute } from '${importPath}'

export function AnalyticsProvider({ children }: { children: React.ReactNode }) {
  const pathname = usePathname()
  useEffect(() => { void initAnalytics() }, [])
  useEffect(() => { if (pathname) syncRoute(pathname) }, [pathname])
  return <>{children}</>
}
`
  }
  if (framework === 'react' || framework === 'remix' || framework === 'solid') {
    return `import { useEffect } from 'react'
import { useLocation } from 'react-router-dom'
import { initAnalytics, syncRoute } from '${importPath}'

export function useAnalytics() {
  const location = useLocation()
  useEffect(() => { void initAnalytics() }, [])
  useEffect(() => { syncRoute(location.pathname) }, [location.pathname])
}
`
  }
  if (framework === 'sveltekit' || framework === 'svelte') {
    return `<script lang="ts">
  import { onMount } from 'svelte'
  import { page } from '$app/stores'
  import { initAnalytics, syncRoute } from '${importPath}'

  onMount(() => { void initAnalytics() })
  $: if ($page.url.pathname) syncRoute($page.url.pathname)
</script>
`
  }
  if (framework === 'nuxt' || framework === 'vue') {
    return `import { watch } from 'vue'
import { useRoute } from 'vue-router'
import { initAnalytics, syncRoute } from '${importPath}'

export function useAnalytics() {
  const route = useRoute()
  void initAnalytics()
  watch(() => route.path, (path) => syncRoute(path), { immediate: true })
}
`
  }
  return `import { initAnalytics, syncRoute } from '${importPath}'

void initAnalytics()
syncRoute(window.location.pathname)
// Call syncRoute(path) again on every client-side navigation.
`
}
