/**
 * Generate ANALYTICS.md.
 *
 * A dashboard nobody can read is a dashboard nobody opens. This writes the
 * document that turns six pages of charts into a routine: what to look at on a
 * Monday, what each number means, what to do when it moves, and what is missing
 * from the picture and why.
 *
 * It is written from the same plan the dashboards were built from, so it can
 * never describe a tile that was skipped or omit one that was created.
 */

import type { CreatedDashboard, PackDashboard, TrackingPlan } from '../types.js'
import type { SkippedTile } from '../posthog/sync.js'
import { ROLE_DESCRIPTIONS, type EventRole } from '../plan/roles.js'

export interface WalkthroughOptions {
  plan: TrackingPlan
  dashboards: PackDashboard[]
  created: CreatedDashboard[]
  skipped: SkippedTile[]
  projectUrl: string
  analyticsModulePath?: string
}

function dashboardUrl(created: CreatedDashboard[], name: string): string | undefined {
  return created.find((dashboard) => dashboard.name === name)?.url
}

export function emitWalkthrough(options: WalkthroughOptions): string {
  const { plan, dashboards, created, skipped, projectUrl } = options
  const emitted = plan.events.filter((event) => event.emitted)
  const suggested = plan.events.filter((event) => !event.emitted)
  const tileCount = dashboards.reduce((total, dashboard) => total + dashboard.tiles.length, 0)

  const lines: string[] = []
  const push = (...text: string[]) => lines.push(...text)

  push(
    `# Analytics for ${plan.product.name}`,
    '',
    `${plan.product.description}`,
    '',
    `> Generated by [OpenHog](https://github.com/ZakKrevitt/OpenHog) from this repository on ${plan.generatedAt.slice(0, 10)}.`,
    `> ${dashboards.length} dashboards, ${tileCount} charts, built on the ${emitted.length} events this codebase actually emits.`,
    '',
    '---',
    '',
    '## The 5-minute version',
    '',
    'If you do nothing else, do this once a week:',
    '',
  )

  const northStar = dashboards.find((dashboard) => dashboard.key === 'north-star')
  if (northStar) {
    const url = dashboardUrl(created, northStar.name)
    push(
      `1. Open **${northStar.name}**${url ? ` (${url})` : ''}.`,
      '2. Look at the **activation funnel** and find the steepest single drop. That step is your next piece of work — not the step with the fewest people, the step with the biggest percentage fall.',
      '3. Look at the **retention curve**. Read the first column downwards. If it falls to zero by week 4 you have a leaky bucket, and no amount of acquisition will fill it.',
      '4. Open **Instrumentation health** and check the "planned events that have stopped arriving" tile is empty. If it is not, one of the charts you just read is lying to you.',
      '',
      'That is the whole routine. Everything below is detail for when a number moves and you need to know why.',
      '',
    )
  }

  push('---', '', '## What each dashboard is for', '')

  for (const dashboard of dashboards) {
    const url = dashboardUrl(created, dashboard.name)
    push(
      `### ${dashboard.name}`,
      '',
      `**The question it answers:** ${dashboard.question}`,
      '',
      dashboard.description,
      '',
      url ? `[Open in PostHog](${url})` : '',
      '',
    )
    for (const tile of dashboard.tiles) {
      push(
        `#### ${tile.name}`,
        '',
        `*${tile.description}*`,
        '',
        `**How to read it.** ${tile.interpretation}`,
        '',
      )
    }
    push('---', '')
  }

  // ---------------------------------------------------------------------
  // Gaps
  // ---------------------------------------------------------------------
  if (skipped.length || suggested.length) {
    push(
      '## What is missing, and what it would unlock',
      '',
      'OpenHog only builds a chart when your code actually emits the events it needs. That is deliberate: a dashboard of empty tiles is worse than a smaller dashboard, because you stop trusting all of it.',
      '',
    )

    if (suggested.length) {
      push(
        `These ${suggested.length} events are not emitted yet. Each one is listed with where it probably belongs.`,
        '',
        '| Event | Why it matters | Where it goes |',
        '| --- | --- | --- |',
      )
      for (const event of suggested.slice(0, 30)) {
        const where = event.suggestedLocations?.[0] ?? '—'
        push(`| \`${event.name}\` | ${event.description.replace(/\|/g, '\\|')} | ${where.replace(/\|/g, '\\|')} |`)
      }
      push('')
    }

    if (skipped.length) {
      const byDashboard = new Map<string, string[]>()
      for (const item of skipped) {
        const list = byDashboard.get(item.dashboard) ?? []
        list.push(item.tile)
        byDashboard.set(item.dashboard, list)
      }
      push('Charts that would appear once those events exist:', '')
      for (const [dashboard, tiles] of byDashboard) {
        push(`- **${dashboard}** — ${tiles.join(', ')}`)
      }
      push('', 'Add the events, then run `openhog sync` again. The new charts appear automatically.', '')
    }
    push('---', '')
  }

  // ---------------------------------------------------------------------
  // Events reference
  // ---------------------------------------------------------------------
  push(
    '## The events',
    '',
    `\`${emitted.length}\` events are emitted by this codebase. They are the only thing the dashboards above are built on.`,
    '',
  )

  const stages: [string, string][] = [
    ['acquisition', 'Acquisition — how people arrive'],
    ['activation', 'Activation — the first time it works'],
    ['engagement', 'Engagement — ongoing use'],
    ['conversion', 'Conversion — money'],
    ['retention', 'Retention — coming back'],
    ['referral', 'Referral — bringing others'],
    ['health', 'Health — things going wrong'],
  ]

  for (const [stage, heading] of stages) {
    const inStage = emitted.filter((event) => event.stage === stage)
    if (!inStage.length) continue
    push(`### ${heading}`, '', '| Event | Fires | Emitted from |', '| --- | --- | --- |')
    for (const event of inStage) {
      const source = event.sources[0] ?? '—'
      push(
        `| \`${event.name}\` | ${event.description.replace(/\|/g, '\\|').slice(0, 160)} | \`${source}\` |`,
      )
    }
    push('')
  }

  // ---------------------------------------------------------------------
  // Role map
  // ---------------------------------------------------------------------
  const roleEntries = Object.entries(plan.roles)
  if (roleEntries.length) {
    push(
      '---',
      '',
      '## How the dashboards found your events',
      '',
      'Dashboard packs are written against *roles*, not literal event names, because every codebase names things differently. This is the mapping OpenHog resolved for you.',
      '',
      '**If a row here is wrong, fix it in `openhog/tracking-plan.json` and re-run `openhog sync`.** One corrected line fixes every chart that used it.',
      '',
      '| Role | Your event | What the role means |',
      '| --- | --- | --- |',
    )
    for (const [roleName, eventName] of roleEntries) {
      const description = ROLE_DESCRIPTIONS[roleName as EventRole] ?? ''
      push(`| \`${roleName}\` | \`${eventName}\` | ${description} |`)
    }
    push('')
  }

  // ---------------------------------------------------------------------
  // Operating notes
  // ---------------------------------------------------------------------
  push(
    '---',
    '',
    '## Adding an event',
    '',
    '1. Add the name to `EVENT_NAMES` in `' + (options.analyticsModulePath ?? 'your analytics module') + '`. The type is derived from that array, so a typo at a call site becomes a compile error.',
    '2. Call `track(name, properties)`.',
    '3. Prefer buckets over raw values. `price_bucket: "under_20"` is useful forever; `price: 19.99` is a thousand distinct property values that break every breakdown and cost money.',
    '4. Run `openhog check` to confirm the plan and the code agree.',
    '',
    '### Properties that are always worth sending',
    '',
    '- `surface` — which part of the product. Turns every count into a comparison.',
    '- `route` — the normalised route. Already added for you by the generated module.',
    '- `source` — what triggered it: a button, a deep link, a notification.',
    '',
    '### Properties that will hurt you',
    '',
    '- Raw ids, emails, usernames, or anything else unique to one person.',
    '- Raw search queries. Bucket the length instead; the text is high cardinality and frequently personal.',
    '- Raw prices, timings and counts as breakdown values. Bucket them.',
    '- Full URLs. The generated module already normalises them, but do not add your own.',
    '',
    'The **Instrumentation health** dashboard has a tile that catches all of these after the fact. Check it monthly.',
    '',
    '---',
    '',
    '## Four failures that only appear in production',
    '',
    'Every one of these has shipped, silently, in a real product. The generated analytics module already prevents all four. They are written down because the day someone "simplifies" that file, this is what breaks.',
    '',
    '1. **CSP directives are separate allowlists.** A host in `connect-src` is not thereby loadable as a script. PostHog\'s asset host serves the session-replay recorder as a *script*, so replay needs it in `script-src` too. Miss that and events flow forever while `$recording_status` sits at `lazy_loading` and you get zero recordings. Dev serves no CSP at all, so this is invisible until production.',
    '2. **`capture_pageview: "history_change"` skips the first load.** It captures on history changes only, so a full page load sends `$pageleave` with no matching `$pageview`. Every direct visit and every reload goes uncounted and Web Analytics reads near zero. The generated module sends `$pageview` by hand instead.',
    '3. **Sanitising `$current_url` down to a bare path breaks Web Analytics.** It parses that field to attribute a visit to a domain, so stripping the origin attributes every visit to nothing. Strip the ids and the query string; keep the origin.',
    '4. **Session replay starts on the first navigation, not on landing.** The SDK is imported dynamically, so the first route effect runs before the instance exists. Land-look-leave sessions — the ones most worth watching — are exactly the ones never recorded. The generated module catches up to the current route after the import resolves.',
    '',
    'Run `openhog doctor` to check all four, plus your CSP, your env vars, and whether events are actually arriving.',
    '',
    '---',
    '',
    '## Privacy',
    '',
    'The generated setup is conservative by default:',
    '',
    '- **Autocapture is off.** Only events someone deliberately named are sent. A new button cannot start reporting itself.',
    '- **URLs are normalised** before they leave the browser, so ids and share codes never become property values.',
    '- **`respect_dnt` is on**, and person profiles are created only for identified users.',
    '- **Session replay is off unless you turn it on**, and even then it never runs on these routes:',
    '',
    ...(plan.identity.sensitiveRoutes.length
      ? plan.identity.sensitiveRoutes.map((route) => `  - \`${route}\``)
      : ['  - _(none detected — check this list is right)_']),
    '',
    '  Add a route to `SENSITIVE_ROUTES` the moment it starts showing someone else\'s personal data. Recording a masked password field is one thing; recording the shape of someone\'s inbox is another, and no masking selector makes that safe.',
    '',
    '---',
    '',
    '## Commands',
    '',
    '```bash',
    'openhog doctor    # why is nothing arriving? checks CSP, env, SDK, live ingest',
    'openhog check     # does the code still match the tracking plan? (exit 1 on drift)',
    'openhog sync      # rebuild dashboards after editing the plan',
    'openhog demo      # seed realistic data so the dashboards are not empty',
    '```',
    '',
    `PostHog project: ${projectUrl}`,
    '',
  )

  return lines.filter((line) => line !== undefined).join('\n').replace(/\n{3,}/g, '\n\n')
}
